/**
 * Deepak Trading Corp - Premium B2B Road & Traffic Safety Catalog Data
 * This file serves as the clientside B2B product registry.
 * (Sorted in Systematic Chronological Category-wise & Brand-wise Order)
 */

const products = [
  // ==================== 1. ROAD STUDS & FIXATIVES (road-studs) ====================
  {
    id: "prod-3m-rpm-shank",
    views: 2334,
    likes: 541,
    brand: "3m",
    name: "3M Raised Pavement Marker (RPM) - Twin Molded Shank",
    category: "road-studs",
    image: "assets/3m_rpm_shank.png",
    installationImage: "assets/3m_rpm_shank_installation.jpg",
    physicalImage: "assets/3m_rpm_shank_physical.png",
    description: "Premium Raised Pavement Marker specifically engineered for low-light Indian road conditions. Features a dual molded shank for ultimate physical anchoring into asphalt, a 16 sq.cm high-reflectivity lens area, and 16-ton heavy-duty load bearing capacity.",
    isAuthorized3MPartner: true,
    trustBadge: "3M Authorized Partner",
    isBestSeller: true,
    moq: 100,
    specs: {
      "Reflective Area": "16 sq.cm",
      "Height": "16 ± 0.1 mm",
      "Width": "101.1 ± 0.1 mm",
      "Length": "88.9 ± 0.1 mm",
      "Slope": "30.5 ± 0.1 Degrees",
      "Shank Length": "30 ± 2 mm",
      "Shank Diameter": "20 mm",
      "Load Bearing Capacity": "16 Tons",
      "Lens Colors": "Red, Yellow, White, Green, Red & White",
      "Standard Compliance": "IRC Approved Specification"
    }
  },
  {
    id: "prod-3m-rpm-nextgen",
    views: 980,
    likes: 315,
    brand: "3m",
    name: "3M Raised Pavement Marker (RPM) - Next Generation",
    category: "road-studs",
    image: "assets/3m_rpm_nextgen.png",
    installationImage: "assets/3m_rpm_nextgen_installation.png",
    physicalImage: "assets/3m_rpm_nextgen_physical.png",
    description: "Low-profile, highly durable Raised Pavement Marker specifically engineered for low-light Indian road conditions. Features a finger-ridge design for smooth tire transitions, 16 sq.cm reflective area, and 13.5-ton load capacity.",
    isAuthorized3MPartner: true,
    trustBadge: "3M Authorized Partner",
    isBestSeller: false,
    moq: 100,
    specs: {
      "Reflective Area": "16 sq.cm",
      "Height": "18 ± 0.8 mm",
      "Width": "80 ± 0.5 mm",
      "Length": "89 ± 0.5 mm",
      "Slope": "30.5 ± 0.1 Degrees",
      "Load Bearing Capacity": "13.5 Tons",
      "Lens Colors": "Red, Yellow, White",
      "Standard Compliance": "IRC Approved Specification"
    }
  },
  {
    id: "prod-3m-rpm-ilc",
    views: 900,
    likes: 288,
    brand: "3m",
    name: "3M Raised Pavement Marker (RPM) - ILC Non Shank",
    category: "road-studs",
    image: "assets/3m_rpm_ilc.png",
    installationImage: "assets/3m_rpm_ilc_installation.png",
    physicalImage: "assets/3m_rpm_ilc_physical.jpg",
    description: "Flat-mount Raised Pavement Marker specifically engineered for solid concrete or bridge decks where shanks are not suitable. Features a 16 sq.cm highly retroreflective prismatic lens, 30.5-degree slope, and direct adhesive application.",
    isAuthorized3MPartner: true,
    trustBadge: "3M Authorized Partner",
    isBestSeller: false,
    moq: 100,
    specs: {
      "Reflective Area": "16 sq.cm",
      "Height": "18 ± 0.8 mm",
      "Width": "101.1 ± 0.1 mm",
      "Length": "88.9 ± 0.1 mm",
      "Slope": "30.5 ± 0.1 Degrees",
      "Lens Colors": "Red, White, Yellow, Red & White",
      "Mounting Style": "ILC Non-Shank Adhesive Layout"
    }
  },
  {
    id: "prod-3m-rpm-solar",
    views: 1531,
    likes: 517,
    brand: "3m",
    name: "Solar Raised Pavement Marker",
    category: "road-studs",
    image: "assets/3m_rpm_solar.png",
    gallery: [
      { src: "assets/3m_rpm_solar_physical.png", alt: "Physical View" },
      { src: "assets/3m_rpm_solar_physical.jpg", alt: "Physical Product Photo" }
    ],
    description: "Premium solar-powered raised pavement marker engineered under rigid 3M highway safety guidelines. Features an integrated active solar LED module, heat-resistant storage, a solid physical shank anchoring, and high-intensity body visibility.",
    isAuthorized3MPartner: true,
    trustBadge: "3M Authorized Partner",
    isBestSeller: true,
    moq: 50,
    specs: {
      "Diameter": "136 ± 4 mm",
      "Height": "65 ± 2 mm",
      "Shank Length": "40 mm",
      "Shank Diameter": "25 mm",
      "Shank Breakage Strength": "820 kgf",
      "Body Colors Available": "Yellow Body, White Body",
      "Standard Compliance": "3M Highway Safety Standards"
    }
  },
  {
    id: "prod-3m-rpm-polycarbonate",
    views: 1479,
    likes: 405,
    brand: "3m",
    name: "3M Raised Pavement Marker (RPM) - Polycarbonate Road Stud",
    category: "road-studs",
    image: "assets/3m_rpm_polycarbonate.png",
    physicalImage: "assets/3m_rpm_polycarbonate_physical.jpg",
    description: "Extremely rugged polycarbonate raised pavement marker designed for low-light Indian road corridors. Engineered with a massive 13.5-ton load bearing capacity, a 16 sq.cm reflective prism area, and highly durable structural thermoplastic construction.",
    isAuthorized3MPartner: true,
    trustBadge: "3M Authorized Partner",
    isBestSeller: false,
    moq: 100,
    specs: {
      "Reflective Area": "16 sq.cm",
      "Height": "18 ± 0.8 mm",
      "Width": "101.1 ± 0.1 mm",
      "Length": "88.9 ± 0.1 mm",
      "Slope": "30.5 ± 0.1 Degrees",
      "Load Bearing Capacity": "13.5 Tons",
      "Lens Colors": "Red, Red & White, Yellow, White",
      "Standard Compliance": "IRC Certified Specification"
    }
  },
  {
    id: "prod-detco-epoxy",
    views: 2078,
    likes: 496,
    brand: "detco",
    name: "DETCO Premium Road Safety Epoxy Kit",
    category: "road-studs",
    image: "assets/detco_epoxy_kit.jpg",
    installationImage: "assets/detco_epoxy_installation.jpg",
    physicalImage: "assets/detco_epoxy_physical.jpg",
    description: "High-tensile industrial-grade road safety epoxy bonding compound kit formulated specifically for the rigid anchoring and fixing of Raised Pavement Markers (RPM) and lane markers on heavy-traffic national highways.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: true,
    moq: 10,
    specs: {
      "Part A Resin": "1 kg pack",
      "Part B Hardener": "1/2 kg pack",
      "Part C Filler": "3 kg pack",
      "Mixing Ratio": "Standardized compound mixing guidelines",
      "Usable Time": "15 - 30 Minutes",
      "Setting Time": "40 - 55 Minutes",
      "Yield / Coverage": "Sufficient to fix approximately 22-25 Raised Pavement Markers (RPM)",
      "Logo Markings": "Official DETCO D C Shield Logo print",
      "Material": "High-Tensile Polyurethane/Epoxy Polymer Blend",
      "Standard Compliance": "IRC Highway Specifications Approved"
    }
  },
  {
    id: "prod-3m-epoxy-kit",
    views: 1861,
    likes: 299,
    brand: "3m",
    name: "3M Epoxy Kit for RPM Application",
    category: "road-studs",
    image: "assets/3m_epoxy_kit.jpg?v=1.2",
    installationImage: "assets/3m_epoxy_kit_installation.jpg?v=1.2",
    description: "3M Epoxy Kit for RPM Application is a high-performance, three-part epoxy system formulated specifically for the high-strength bonding of Raised Pavement Markers (RPMs) and road studs onto asphalt and concrete road surfaces. Comprising Part A (Resin), Part B (Hardener), and Part C (Filler/Sand), this 9 kg kit is sufficient for installing approximately 100 road studs, providing excellent impact strength, weatherproofing, and rapid cure times to withstand extreme traffic loads.",
    isAuthorized3MPartner: true,
    trustBadge: "3M Authorized Partner",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Product Composition": "3-Part Kit (Part A Resin, Part B Hardener, Part C Filler)",
      "Net Quantity": "Part A + B + C (Total 9 kg kit)",
      "Yield / Coverage": "100 Road Studs per Epoxy Kit can be used",
      "Applications": "Heavy-duty Raised Pavement Marker (RPM) & Road Stud road anchoring",
      "Curing Profile": "Rapid setting under ambient highway temperatures",
      "Impact Strength": "High impact load bearing capacity under highway traffic",
      "Features": "Excellent moisture resistance, durable adhesion to concrete/asphalt",
      "Standard Compliance": "3M Road Transportation Safety & IRC Specifications"
    }
  },


  {
    id: "prod-darkeye-da110-solar",
    views: 2240,
    likes: 745,
    brand: "darkeye",
    name: "Dark Eye DA 110 Solar-Powered Road Stud",
    category: "road-studs",
    image: "assets/darkeye_da110_solar.jpg?v=34.0",
    description: "Heavy-duty monocrystalline solar road stud engineered for maximum visibility and long-term durability. Features built-in LSD technology, robust battery performance, and custom installation warnings to provide 24/7 visual guidance along road shoulders.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: true,
    moq: 50,
    specs: {
      "Solar Panel": "Mono-Crystalline Solar 2.4 V / 0.3 Watt",
      "LED Color": "Red",
      "Battery": "1.2V Ni-MH rechargeable battery capacity 1300 mAh",
      "LSD Technology": "Low Self Discharge fitted inside",
      "Working Time": "2 – 3 days successively after fully charged",
      "Dimensions": "125 x 125 x 25 mm",
      "Shank Length": "65 mm approx",
      "Weight": "Approx 670 grams",
      "Installation Instructions": "To be installed only on sides and not in center of the roads"
    }
  },
  {
    id: "prod-darkeye-da56-reflective",
    views: 1278,
    likes: 290,
    brand: "darkeye",
    name: "Dark Eye DA 56 Aluminium Alloy Two-Way Reflective Road Stud",
    category: "road-studs",
    image: "assets/darkeye_da56_reflective.jpg?v=34.0",
    description: "Heavy-duty two-way reflective road stud manufactured from high-grade cast aluminium alloy. Featuring amber, red, or white prismatic reflector panels, engineered to withstand extreme physical impacts and high highway load bearings.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: false,
    moq: 100,
    specs: {
      "Dimensions": "100 x 8 x 20 mm",
      "Body Material": "Aluminium alloy",
      "Reflector Panel Colors": "Amber, Red or White",
      "Weight": "185 grams",
      "Load Bearing Style": "Two-Way Reflective Surface"
    }
  },
  {
    id: "prod-darkeye-da110-dhruv",
    views: 1085,
    likes: 175,
    brand: "darkeye",
    name: "Dark Eye DA 110 Solar Stud - Dhruv Gem",
    category: "road-studs",
    image: "assets/darkeye_da110_dhruv.jpg?v=34.0",
    description: "Premium high-efficiency solar road stud featuring 6 superbright LEDs with 18,000 mcd intensity, IP68 waterproof design, and mono-crystalline solar panels. Delivers outstanding performance for long-range visibility and safety in toll plazas, highways, and dark curves.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: false,
    moq: 30,
    specs: {
      "Solar Panel": "High Efficiency 22.8% Mono-Crystalline 3 V",
      "Battery": "OneNi-Mh-A82 LSD Rechargeable Battery 1.2V High Temperature",
      "LEDs": "Six Superbright LEDs with 18,000mcd",
      "Dimensions": "110 x 110 x 26 mm approx",
      "View Distance": "Up to 1000 m",
      "Flash Rate": "1Hz or according to customer requirements",
      "LED Colors": "Red, Amber, or custom client choice",
      "Charging Time": "5-6 hours/day",
      "Working Time": "50 hours successively after fully charged",
      "Waterproof Rating": "100% waterproof design confirms to IP68"
    }
  },

  // ==================== 2. RETROREFLECTIVE HIGHWAY TAPES & SHEETING (reflective-tapes) ====================
  {
    id: "prod-reflective-tape-hip",
    views: 1614,
    likes: 554,
    brand: "3m",
    name: "3M High Intensity Prismatic (HIP) Sheeting Series 3430",
    category: "reflective-tapes",
    image: "assets/3m_egp_sheeting.png",
    gallery: [
      { src: "assets/3m_hip_sheeting_variants.jpg?v=1.2", alt: "3M High Intensity Prismatic (HIP) Sheeting Color Roll Variants" }
    ],
    description: "HP 3430 3M is engineered to offer versatile \"EGP\" grade prismatic retro-reflective sheeting. It works across several sign applications, backed by reliable 3M performance warranty. Ideal for road signage, traffic safety, and high conspicuity safety and security applications.",
    isAuthorized3MPartner: true,
    trustBadge: "3M Authorized Partner",
    isBestSeller: true,
    moq: 10,
    specs: {
      "Standard Size of Roll": "4 ft x 150 ft (Size can be customized as per requirement)",
      "Color Codes Available": "3430 White, 3431 Yellow, 3432 Red, 3435 Blue, 3437 Green",
      "Sheeting Class": "Type I, Class A",
      "Features": "Self Adhesive, UV Stabilized, Weather Resistant, High Intensity Superior Brightness",
      "Application": "Ideal for road signage, traffic safety, and high conspicuity safety and security applications",
      "Standard Compliance": "3M Highway Sheeting & Retroreflective Standards"
    }
  },
  {
    id: "prod-reflective-tape-conspicuity",
    views: 1953,
    likes: 434,
    brand: "3m",
    name: "3M Diamond Grade Reflective Sheeting Series 4090",
    category: "reflective-tapes",
    image: "assets/3m_dg_sheeting.jpg?v=32.0",
    gallery: [
      { src: "assets/3m_dg_sheeting.png?v=32.0", alt: "3M Diamond Grade Reflective Sheeting Roll" }
    ],
    description: "3M DG is currently the benchmark for reflective films across the world. Incorporating 'full cube' technology for phenomenal performance DG's optical elements are 100% efficient and reflect up to 60% of available light (the highest compared to regular prismatic films). DG's superior optical quality means enhanced visibility at all sight distances (including medium and short distances) and even in awkward sign positions.",
    isAuthorized3MPartner: true,
    trustBadge: "3M Authorized Partner",
    isBestSeller: true,
    moq: 15,
    specs: {
      "Standard Size of Roll": "4 ft x 150 ft (Size can be customized as per requirement)",
      "Color Codes Available": "4090 White, 4091 Yellow",
      "Sheeting Class": "Type XI, Class C",
      "Features": "Full Cube Technology, 100% Efficient Optical Elements, Superior Reflectivity",
      "Visibility": "Enhanced visibility at all sight distances (including medium and short distances)",
      "Standard Compliance": "3M Highway Sheeting & Retroreflective Standards"
    }
  },
  {
    id: "prod-3m-antiskid",
    views: 1822,
    likes: 540,
    brand: "3m",
    name: "3M Heavy-Duty Anti-Skid Safety Traction Tape",
    category: "reflective-tapes",
    image: "assets/3m_antiskid.png",
    gallery: [
      { src: "assets/3m_antiskid_studio.jpg", alt: "Studio View (Black Rolls)" },
      { src: "assets/3m_antiskid_variant.jpg", alt: "Variants View (Black, Yellow & Warning)" },
      { src: "assets/3m_antiskid_roll_warning.jpg", alt: "Physical View (Warning Tape Roll)" },
      { src: "assets/3m_antiskid_stairs.jpg", alt: "Staircase Installation" },
      { src: "assets/3m_antiskid_floor.jpg", alt: "Floor Installation" },
      { src: "assets/3m_antiskid_ramp.jpg", alt: "Ramp Installation" }
    ],
    description: "Premium abrasive slip-resistant safety tape designed to provide a highly secure slip-resistant surface on steps, stairways, industrial ramps, docks, and machinery platforms under extreme conditions.",
    isAuthorized3MPartner: true,
    trustBadge: "3M Authorized Partner",
    isBestSeller: true,
    moq: 15,
    specs: {
      "Size": "1/2 inch x 18 Meters (1/2\" x 18mtrs)",
      "Colors Available": "Black, Yellow, Clear, Yellow-Black Warning",
      "Features": "High Grip Traction, Waterproof, Extremely Durable",
      "Application": "Easy installation on stairs, ramps, floors, and equipment",
      "Standard Compliance": "3M Highway Safety & Traction Standards"
    }
  },
  {
    id: "prod-3m-afp-sheeting",
    views: 2282,
    likes: 407,
    brand: "3m",
    name: "3M Aluminium Backed Flexible Prismatic (AFP) Sheeting",
    category: "reflective-tapes",
    image: "assets/3m_afp_sheeting.png",
    physicalImage: "assets/3m_afp_sheeting_physical.jpg",
    description: "AFP is a new generation flexible sheeting designed for high visibility in harsh road conditions. It features an integrated aluminum backing that provides excellent mechanical strength and durability, allowing it to easily conform and adhere directly to rough concrete surfaces and trees.",
    isAuthorized3MPartner: true,
    trustBadge: "3M Authorized Partner",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Variants & Sizes Available": "Slant, Arrow, Plain options",
      "Backing Type": "Durable Aluminium Backed layout",
      "Reflective Surface": "High intensity reflective prismatic sheeting",
      "Features": "Flexible Sheeting conforms easily to rough & curved surfaces",
      "Application": "Can be easily applied directly on rough concrete surfaces and trees",
      "Standard Compliance": "3M Highway Sheeting & Retroreflective Standards"
    }
  },
  {
    id: "prod-3m-electrocut-1170",
    views: 1778,
    likes: 603,
    brand: "3m",
    name: "3M ElectroCut Film Series 1170",
    category: "reflective-tapes",
    image: "assets/3m_electrocut_1170.png?v=1.2",
    gallery: [
      { src: "assets/3m_electrocut_1170_physical.jpg?v=1.2", alt: "Physical View (Transparent Film)" },
      { src: "assets/3m_electrocut_1170_peel.png?v=1.2", alt: "Overlay Peeling Detail" },
      { src: "assets/3m_electrocut_1170_graffiti.png?v=1.2", alt: "Anti-Graffiti Cleaning Performance" }
    ],
    description: "3M ElectroCut Film Series 1170 is a durable, transparent, acrylic film coated with a transparent, pressure-sensitive adhesive protected by a removable liner. Designed for application over 3M reflective sheeting to create high-visibility multi-colored traffic signs, directional guides, and municipal warning signboards with long-lasting weather and graffiti resistance.",
    isAuthorized3MPartner: true,
    trustBadge: "3M Authorized Partner",
    isBestSeller: false,
    moq: 5,
    specs: {
      "Product Code": "1170 Series",
      "Color Codes Available": "1171 Yellow, 1172 Red, 1174 Orange, 1175 Blue, 1177 Green",
      "Adhesive Type": "Transparent, pressure-sensitive",
      "Liner": "Removable protective liner",
      "Material": "Premium durable transparent acrylic",
      "Application": "Applied over reflective sheeting for sign graphics & protective overlay",
      "Features": "Graffiti-resistant, weather-proof, easy weeding",
      "Standard Compliance": "3M Transportation Safety & Highway Sign Standards"
    }
  },
  {
    id: "prod-detco-floor-marking-tape",
    views: 1782,
    likes: 445,
    brand: "detco",
    name: "DETCO Premium Floor Marking Tape",
    category: "reflective-tapes",
    image: "assets/detco_floor_marking_tape.jpg?v=1.2",
    installationImage: "assets/detco_floor_marking_tape_installation.jpg?v=1.2",
    description: "High-durability, self-adhesive industrial floor marking tape designed for color-coded lane marking, safety zoning, and hazard demarcation in warehouses, manufacturing plants, and commercial facilities.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: true,
    moq: 10,
    specs: {
      "Width": "2 inches (50 mm)",
      "Length": "33 meters",
      "Colors Available": "Yellow, Red, Blue, Green, Black, White, Orange, Yellow-Black Warning, Red-White Warning",
      "Adhesive Type": "High-tack pressure-sensitive adhesive",
      "Material": "Heavy-duty PVC / Vinyl compound",
      "Application": "Warehouse walkways, safety zoning, hazard marking, pathway guidance",
      "Customization": "Sizes and colors can be customized as per requirements",
      "Standard Compliance": "Industrial OSHA & Safety Color Standards"
    }
  },
  {
    id: "prod-3m-conspicuity-tape",
    views: 1314,
    likes: 223,
    brand: "3m",
    name: "3M Conspicuity Tapes",
    category: "reflective-tapes",
    image: "assets/3m_conspicuity_tape.png?v=1.2",
    gallery: [
      { src: "assets/3m_conspicuity_tape_spec.jpg?v=1.2", alt: "3M 983 Conspicuity Tape Specification Diagram" },
      { src: "assets/3m_conspicuity_tape_truck_side.png?v=1.2", alt: "Yellow Conspicuity Tape Truck Side Outline View" },
      { src: "assets/3m_conspicuity_tape_truck_back.png?v=1.2", alt: "Red & White Conspicuity Tape Truck Back View" },
      { src: "assets/conspicuity_tape_scenic_truck.png?v=1.2", alt: "Scenic Highway Conspicuity Tape Installation on White Box Truck" },
      { src: "assets/conspicuity_tape_dusk_side.png?v=1.2", alt: "Yellow Conspicuity Tape Reflective Dusk Performance" },
      { src: "assets/conspicuity_tape_tractor.jpg?v=1.2", alt: "Reflective Strip Installation on Tractor Front Hood" }
    ],
    description: "3M 983 Conspicuity Sheeting with polycarbonate microprisms designed to give nighttime vehicle visibility a whole new level of brightness. Engineered for extreme road and weather conditions with long-lasting reflectivity and strong adhesion.",
    isAuthorized3MPartner: true,
    trustBadge: "3M Authorized Partner",
    isBestSeller: true,
    moq: 10,
    specs: {
      "Standard Size of Roll": "2 inches x 50 meters (Size can be customized as per requirement)",
      "Colors Available": "White, Red, Yellow, White & Red",
      "Material": "Polycarbonate microprisms film with heavy-duty backing",
      "Features": "Polycarbonate Microprisms, Extreme Road Conditions Durability, High Visibility",
      "Application": "Commercial trucks, trailers, utility vehicles lane & hazard marking",
      "Standard Compliance": "3M Transportation Safety & Highway Standards"
    }
  },

  // ==================== 3. TRAFFIC CONES, DELINEATORS & POSTS (traffic-cones) ====================
  {
    id: "prod-3m-delineator",
    views: 1180,
    likes: 402,
    brand: "3m",
    name: "3M Standard Delineator",
    category: "traffic-cones",
    image: "assets/3m_delineator.jpg",
    installationImage: "assets/3m_delineator_installation.jpg",
    description: "3M Delineator is engineered to deliver years of all-weather visibility, safety, durability and elegance. It is an innovative product and gives unmatched visibility and reliable performance.",
    isAuthorized3MPartner: true,
    trustBadge: "3M Authorized Partner",
    isBestSeller: true,
    moq: 20,
    specs: {
      "Total Height": "1000 mm",
      "Impact Strength": "600 J/m",
      "Thickness": "80 mm",
      "Base Depth": "200 mm",
      "Reflective Sleeves": "Authentic 3M Microprismatic Reflective Collars",
      "Standard Compliance": "3M Highway Safety Standards"
    }
  },
  {
    id: "prod-3m-median-marker",
    views: 1265,
    likes: 362,
    brand: "3m",
    name: "3M Median Marker",
    category: "traffic-cones",
    image: "assets/3m_median_marker.png?v=1.3",
    gallery: [
      { src: "assets/3m_median_marker_night.jpg?v=1.3", alt: "Nighttime Retroreflective Visibility View" }
    ],
    description: "High-performance flexible median marker engineered to absorb heavy impact and resist deformation. Features a robust 6.5mm body thickness and a 90 sq.cm high-intensity retroreflective surface for maximum day and night visibility on road medians.",
    isAuthorized3MPartner: true,
    trustBadge: "3M Authorized Partner",
    isBestSeller: false,
    moq: 50,
    specs: {
      "Total Height": "180 mm",
      "Body Thickness": "6.5 mm",
      "Reflective Area": "90 sq.cm",
      "Shank Depth": "30 mm",
      "Features": "Flexible Design, High Intensity Reflective Surface, Robust Build",
      "Application": "Quick and easy installation on road medians & traffic islands",
      "Standard Compliance": "3M Highway Safety & Delineation Standards"
    }
  },
  {
    id: "prod-3m-median-marker-standard",
    views: 891,
    likes: 240,
    brand: "3m",
    name: "3M Standard Median Marker",
    category: "traffic-cones",
    image: "assets/3m_standard_median_marker.png?v=32.0",
    gallery: [
      { src: "assets/3m_standard_median_marker_installation.jpg?v=32.0", alt: "Standard Median Marker Road Installation" }
    ],
    description: "Highly durable, rigid rectangular B2B median marker featuring a premium 3M prismatic reflective surface. Built to withstand standard highway impact up to 600J/m, with exceptional weather and water resistance for secure long-term median delineations.",
    isAuthorized3MPartner: true,
    trustBadge: "3M Authorized Partner",
    isBestSeller: true,
    moq: 50,
    specs: {
      "Height": "150 mm",
      "Length": "100 mm",
      "Width": "100 mm",
      "Impact Strength": "600 J/m",
      "Body Material": "Heavy-Duty UV-Stabilized Polycarbonate Casing with Embossed 3M Logo",
      "Reflective Panel": "High-Reflectivity Microprismatic Yellow Sheeting",
      "Base Design": "Pre-drilled Dual Anchoring Holes for Solid Road/Median Bolting",
      "Features": "Durable Build, High Visibility Prismatic Reflective Surface, Strong Impact Resistance",
      "Application": "Quick and secure road median & toll plaza installation",
      "Standard Compliance": "3M Highway Safety & Delineation Standards"
    }
  },
  {
    id: "prod-nilkamal-1000mm-cone",
    views: 2297,
    likes: 796,
    brand: "nilkamal",
    name: "Nilkamal 1000mm Hexagonal Base Traffic Cone",
    category: "traffic-cones",
    image: "assets/nilkamal_1000mm_cone.jpg",
    installationImage: "assets/nilkamal_1000mm_cone_installation.jpg",
    description: "Premium large-scale safety traffic cone manufactured by Nilkamal and customized with DETCO branding. Features a heavy hexagonal base for ultimate wind stability, dual high-intensity reflective safety collars, and a solid 5kg structure. Designed for NHAI highways, expressways, and high-speed construction zoning.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: true,
    moq: 20,
    specs: {
      "Model No": "RMHEXDC1000HW",
      "Dimensions": "1000(L) x 500(W) x 800(H) mm",
      "Weight": "5 kg (approx.)",
      "Material": "Tough UV-Stabilized Polyethylene (HDPE)",
      "Base Design": "Heavy-duty hexagonal base for superior wind resistance",
      "Safety Collars": "Dual high-intensity retroreflective collars for high visibility",
      "Features": "Top slot for safety warning lights or chain loops, stable heavy bottom block",
      "Standard Compliance": "NHAI, PWD & IRC Highway Safety Specifications"
    }
  },
  {
    id: "prod-nilkamal-750mm-cone",
    views: 1537,
    likes: 439,
    brand: "nilkamal",
    name: "Nilkamal 750mm Hexagonal Base Traffic Cone",
    category: "traffic-cones",
    image: "assets/nilkamal_750mm_cone.jpg",
    installationImage: "assets/nilkamal_750mm_cone_installation.jpg",
    description: "Highly stable medium-scale safety traffic cone manufactured by Nilkamal and customized with DETCO branding. Features a heavy-duty hexagonal base and dual high-intensity reflective collars. The industry standard choice for municipal works, toll plazas, and airport taxiways.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: false,
    moq: 30,
    specs: {
      "Model No": "SCHEX750HW / RMHEXDC750",
      "Weight": "4.2 kg / 5.2 kg (approx. variations)",
      "Material": "Tough UV-Stabilized Polyethylene (HDPE)",
      "Base Design": "Heavy-duty hexagonal base for maximum anti-tip wind stability",
      "Safety Collars": "Double high-intensity retroreflective safety collars",
      "Features": "Top carry grip slot, heavy base structure",
      "Standard Compliance": "NHAI, PWD & IRC Safety Guidelines"
    }
  },
  {
    id: "prod-nilkamal-fence-barricade",
    views: 2326,
    likes: 745,
    brand: "nilkamal",
    name: "Nilkamal Fence Barricade",
    category: "traffic-cones",
    image: "assets/nilkamal_fence_barricade.png",
    gallery: [
      { src: "assets/nilkamal_fence_barricade_installation.jpg", alt: "Interlocking Installation View" },
      { src: "assets/nilkamal_fence_barricade_physical.jpg", alt: "Single Barricade View" }
    ],
    description: "Premium interlocking safety fence barricade manufactured by Nilkamal. Features high-density polymer structure with interlocking male-female side connectors for seamless safety zoning, dual detachable support legs, and high-visibility retroreflective safety stripes.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: true,
    moq: 10,
    specs: {
      "Model No": "RMBPF20041000",
      "Dimensions": "2020(L) x 400(W) x 1265(H) mm",
      "Length": "2020 mm",
      "Height": "1265 mm",
      "Width (Base)": "400 mm",
      "Material": "Tough UV-Stabilized Polyethylene (HDPE)",
      "Colors Available": "Bright Red, Bright Yellow",
      "Interlocking System": "Male-Female connector hooks on sides for continuous safety barrier lines",
      "Base Design": "Dual heavy-duty rotating/detachable black support legs",
      "Safety Markings": "High-visibility reflective warning stripes (Red/White or Black/Yellow) on top block",
      "Standard Compliance": "MSRDC & NHAI Road Safety Barrier Specifications"
    }
  },
  {
    id: "prod-nilkamal-trapezium-barricade",
    views: 1232,
    likes: 424,
    brand: "nilkamal",
    name: "Nilkamal Trapezium Barricade",
    category: "traffic-cones",
    image: "assets/detco_trapezium_barricade.jpg",
    installationImage: "assets/nilkamal_trapezium_barricade_installation.jpg",
    description: "Premium water-fillable trapezium traffic safety barrier manufactured by Nilkamal and customized with DETCO branding. Built from highly impact-resistant polymer, featuring a 15-liter water filling capacity for high wind-stability, and an integrated top hazard warning board with diagonal black/yellow safety stripes.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: false,
    moq: 15,
    specs: {
      "Model No": "RMRBH1005800",
      "Dimensions": "1000(L) x 500(W) x 800(H) mm",
      "Length": "1000 mm",
      "Height": "800 mm",
      "Width": "500 mm",
      "Water Capacity": "15 Liters (for high wind ballast)",
      "Material": "Tough UV-Stabilized Polyethylene (HDPE)",
      "Reflective Panel": "Diagonal Black & Yellow warning stripes on top hazard panel",
      "Safety Markings": "Water-fill indicator and custom DETCO embossed branding logos",
      "Base Design": "Wide trapezium base for maximum anti-tip stability",
      "Standard Compliance": "NHAI, PWD & Smart City Traffic Safety Standards"
    }
  },
  {
    id: "prod-nilkamal-1mtr-barricade",
    views: 1966,
    likes: 627,
    brand: "nilkamal",
    name: "Nilkamal 1mtr Barricade",
    category: "traffic-cones",
    image: "assets/detco_1mtr_barricade.jpg",
    installationImage: "assets/nilkamal_1mtr_barricade_installation.png",
    description: "Heavy-duty standalone traffic safety barrier manufactured by Nilkamal and customized with DETCO branding. Specifically designed for high-wind environments, featuring a sand-fillable body for ultimate solid ballast, high-impact polymer engineering, integrated top carrying handles, and dual-tone red and yellow high-visibility indicators.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: false,
    moq: 20,
    specs: {
      "Model No": "RMRBDG10035760",
      "Dimensions": "1000(L) x 350(W) x 760(H) mm",
      "Length": "1000 mm",
      "Height": "760 mm",
      "Width": "350 mm",
      "Ballast Design": "Sand-Fillable (no water leaks or freeze hazards)",
      "Interlocking Design": "None (standalone barrier segments)",
      "Material": "Tough UV-Stabilized Polyethylene (HDPE)",
      "Colors Available": "Bright Red & Bright Yellow",
      "Branding & Features": "Circular DETCO branded logos, dual top integrated carrying handles",
      "Standard Compliance": "NHAI, PWD & Smart City Traffic Management Guidelines"
    }
  },
  {
    id: "prod-nilkamal-2mtr-barricade",
    views: 1591,
    likes: 544,
    brand: "nilkamal",
    name: "Nilkamal 2mtr Barricade",
    category: "traffic-cones",
    image: "assets/detco_2mtr_barricade.jpg",
    installationImage: "assets/nilkamal_2mtr_barricade_installation.jpg",
    description: "Premium large-scale traffic safety barrier manufactured by Nilkamal and customized with DETCO branding. Features a huge 100-liter water capacity for ultimate high-wind stability, male-female interlocking connector hooks on sides for continuous safety zoning, high-visibility retroreflective warning arrows, and UV-stabilized heavy-duty polymer structure.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: true,
    moq: 10,
    specs: {
      "Model No": "RMRBDJ21051000",
      "Dimensions": "2000(L) x 550(W) x 1000(H) mm",
      "Length": "2000 mm",
      "Height": "1000 mm",
      "Width": "550 mm",
      "Water Capacity": "100 Liters (maximum wind-stability ballast)",
      "Material": "Tough UV-Stabilized Polyethylene (HDPE)",
      "Colors Available": "Bright Red, Bright Yellow",
      "Interlocking System": "Male-Female connector hooks on sides for continuous safety barrier lines",
      "Reflectors": "High-visibility reflective warning arrows and top safety reflector panel",
      "Safety Markings": "Circular DETCO branded center logos",
      "Standard Compliance": "NHAI, MSRDC & PWD Road Safety Specifications"
    }
  },
  {
    id: "prod-nilkamal-light-barrier",
    views: 2420,
    likes: 792,
    brand: "nilkamal",
    name: "Nilkamal Light Barrier",
    category: "traffic-cones",
    image: "assets/detco_light_barrier.jpg",
    installationImage: "assets/nilkamal_light_barrier_installation.jpg",
    description: "Anti-glare industrial vertical delineator paddle manufactured by Nilkamal and customized with DETCO branding. Built from highly durable impact-resistant green polymer, featuring high-intensity orange/white retroreflective chevron safety warnings and a slim aerodynamic profile. Designed for highway medians, toll lane routing, and metro safety zones.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: false,
    moq: 50,
    specs: {
      "Model No": "RMHLS6081275",
      "Dimensions": "600(L) x 80(W) x 1275(H) mm",
      "Length": "600 mm",
      "Height": "1275 mm",
      "Width": "80 mm",
      "Material": "Tough UV-Stabilized Polyethylene (HDPE)",
      "Colors Available": "Forest Green base",
      "Chevron Reflectors": "High-intensity orange & white diagonal warning stripes",
      "Branding": "Circular DETCO branded centers",
      "Features": "Anti-glare vertical design, double top carry slots, slim aerodynamic structure",
      "Standard Compliance": "NHAI, MSRDC & PWD Highway Delineator Specifications"
    }
  },
  {
    id: "prod-nilkamal-bull-nose",
    views: 1488,
    likes: 512,
    brand: "nilkamal",
    name: "Nilkamal Bull Nose",
    category: "traffic-cones",
    image: "assets/detco_bull_nose.jpg",
    installationImage: "assets/nilkamal_bull_nose_installation.jpg",
    description: "Premium large-scale crash attenuation and bifurcation barrier manufactured by Nilkamal and customized with DETCO branding. Features a massive 800-liter water ballast capacity for high wind stability and impact energy absorption. Ideal for expressways, highway bifurcation points, exit ramps, and toll plazas.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: true,
    moq: 5,
    specs: {
      "Dimensions": "1185(L) x 1355(W) x 990(H) mm",
      "Length": "1185 mm",
      "Height": "990 mm",
      "Width": "1355 mm",
      "Water Ballast Capacity": "Minimum 800 Liters (for crash energy absorption)",
      "Material": "Tough UV-Stabilized Polyethylene (HDPE)",
      "Color": "Bright Traffic Red",
      "Reflective Panel": "Large white retroreflective safety collar",
      "Application": "Highway bifurcation points, exit ramps, high-speed toll plaza entry safety",
      "Standard Compliance": "NHAI, PWD & Highway Crash Barrier Safety Standards"
    }
  },
  {
    id: "prod-darkeye-da966",
    views: 1087,
    likes: 210,
    brand: "darkeye",
    name: "Dark Eye DA966 Spring Base Delineator",
    category: "traffic-cones",
    gallery: [
      { src: "assets/darkeye_da966_installation.png", alt: "Spring Base Delineator Road Installation View" },
      { src: "assets/darkeye_da966_recovery.png", alt: "Spring Base Delineator Impact Recovery Sequence View" }
    ],
    image: "assets/darkeye_da966.png",
    description: "Highly resilient orange spring-loaded delineator post designed to withstand direct vehicle impacts and return to upright position instantly. Features reflective safety stripes for maximum day and night lane management.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Height": "755 mm",
      "Body Diameter": "74 mm",
      "Base Diameter": "200 mm",
      "Reflective Tape Size": "77 mm",
      "Weight": "830 grams",
      "Base Type": "High-elasticity spring base with anchor holes",
      "Color": "Fluorescent Orange"
    }
  },
  {
    id: "prod-darkeye-da952-fx",
    views: 1292,
    likes: 357,
    brand: "darkeye",
    name: "Dark eye DA 952 FX",
    category: "traffic-cones",
    image: "assets/darkeye_da952_fx.jpg",
    installationImage: "assets/darkeye_da952_fx_installation.jpg",
    description: "Heavy-duty rigid yellow delineator post designed for pedestrian guides, pathway demarcation, and hazard warnings. Equipped with a high-intensity 100mm circular amber reflector top for clear long-distance night visibility.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Height": "1100 mm",
      "Weight": "1750 grams",
      "Reflectors": "100mm dia reflector",
      "Reflector Color": "Yellow",
      "Body Material": "Durable UV-Stabilized Polymer",
      "Anchor Type": "Pointed bottom spike for direct soil/ground anchoring"
    }
  },
  {
    id: "prod-darkeye-anti-glare-barrier",
    views: 1648,
    likes: 302,
    brand: "darkeye",
    name: "Dark Eye Anti Glare Median Barrier",
    category: "traffic-cones",
    image: "assets/darkeye_anti_glare_barrier.png",
    installationImage: "assets/darkeye_anti_glare_barrier_installation.png",
    physicalImage: "assets/darkeye_anti_glare_barrier.jpg",
    description: "Premium anti-glare median delineator barrier designed to prevent high-beam headlight glare from oncoming traffic on highway dividers. Built from tough, impact-resistant green polymer with high-intensity circular orange reflectors.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: false,
    moq: 20,
    specs: {
      "Height Options": "600 mm / 900 mm",
      "Base Dimensions": "150 x 230 mm",
      "Reflectors": "High-intensity circular orange reflectors",
      "Color": "Forest Green",
      "Backing Base": "Robust molded secure anchor base"
    }
  },
  {
    id: "prod-darkeye-da74",
    views: 1604,
    likes: 410,
    brand: "darkeye",
    name: "Dark Eye DA74",
    category: "traffic-cones",
    image: "assets/darkeye_da74.png",
    physicalImage: "assets/darkeye_da74_physical.png",
    description: "Heavy-duty road safety hazard post featuring double 100mm circular orange reflectors and dual vertical amber reflectors. Built from durable all-weather polymer to deliver unmatched long-range visibility and hazard warnings.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Height": "1000 mm",
      "Weight": "1750 grams",
      "Primary Reflectors": "100mm dia x 2 reflectors",
      "Secondary Reflectors": "70mm x 23mm x 2 reflectors",
      "Color": "Clean White base with red/green/yellow neck stripes",
      "Installation Base": "Can be anchored directly into concrete foundations"
    }
  },
  {
    id: "prod-darkeye-da952",
    views: 2135,
    likes: 440,
    brand: "darkeye",
    name: "Dark Eye DA952",
    category: "traffic-cones",
    image: "assets/darkeye_da952.png",
    installationImage: "assets/darkeye_da952_installation.jpg",
    description: "Premium road safety guide post equipped with a caged high-intensity circular yellow reflector top. Engineered to absorb light vehicle impacts and deliver reliable hazard indicators along highway curbs, lanes, and medians.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Height": "600 mm",
      "Weight": "750 grams",
      "Reflectors": "100mm / 65mm dia",
      "Reflector Color": "Yellow",
      "Body Material": "Durable UV-Stabilized Polymer",
      "Protection": "Integrated protective metal/plastic cage top"
    }
  },

  // ==================== 4. HIGHWAY SPEED REGULATION SYSTEMS (speed-breakers) ====================

  {
    id: "prod-darkeye-da1010-speed-bump",
    views: 1152,
    likes: 175,
    brand: "darkeye",
    name: "Dark Eye DA 1010 Heavy-Duty Plastic Speed Bump",
    category: "speed-breakers",
    image: "assets/darkeye_da1010_speed_bump.png",
    description: "Heavy-duty modular plastic speed bump humps engineered for high-performance speed regulation in highways and residential zones. Built from premium high-impact PP plastic with yellow and black interlocking blocks for max day and night visibility.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: true,
    moq: 10,
    specs: {
      "Body Material": "PP plastic material",
      "Length": "252 mm",
      "Width": "352 mm",
      "Height": "50 mm approx",
      "Installation Requirement": "4 Nos. of Nails 4\" are used per pc for installation on road",
      "Weight": "730 grams (2920 grams per mtr)",
      "Installation Suggestion": "We suggest that please filled this Model of Speed Bump with Concrete before installation for long life & better durability"
    }
  },

  // ==================== 5. RETROREFLECTIVE TRAFFIC SIGN BOARDS (sign-boards) ====================


  // ==================== 6. THERMOPLASTIC ROAD MARKING PAINT (marking-paint) ====================
  {
    id: "prod-kataline-traffix",
    views: 1675,
    likes: 452,
    brand: "kataline",
    name: "Kataline Traffix Thermoplastic Road Marking Paint (Commercial Grade)",
    category: "marking-paint",
    image: "assets/kataline_traffix.png",
    specDiagram: "assets/kataline_paint_spec.jpg",
    description: "Commercial Grade Thermoplastic Road Marking Paint designed for durable roads and highways markings. Blended with premium petroleum resin, fillers, and additives for solid adhesion and quick drying time.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: false,
    moq: 40, // 1 Ton (25kg x 40 bags)
    specs: {
      "Product Grade": "Commercial Grade (Traffix)",
      "Specifications": "Commercial Grade MORTH, or any other specification on request",
      "Luminance": "> 65",
      "Softening Point": "102.5° C ± 9.5° C",
      "Application Temp": "160° C - 200° C",
      "Standard Colors": "White / Yellow",
      "Packaging": "25 Kg HDPE Bags",
      "Shelf Life": "12 Months (Store in dry area)",
      "Key Benefits": "High Durability, Excellent Adhesion, High Skid Resistance, Quick Drying Time"
    }
  },
  {
    id: "prod-kataline-traffix-pro",
    views: 2321,
    likes: 569,
    brand: "kataline",
    name: "Kataline Traffix Pro Thermoplastic Road Marking Paint (BS 3262)",
    category: "marking-paint",
    image: "assets/kataline_traffix_pro.png",
    specDiagram: "assets/kataline_paint_spec.jpg",
    description: "Professional Grade Thermoplastic Road Marking Paint certified for British Standard BS 3262 compliance. Delivers superior day and night visibility, excellent skid resistance, and high durability for city streets and highways.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: false,
    moq: 40, // 1 Ton (25kg x 40 bags)
    specs: {
      "Product Grade": "Professional Grade (Traffix Pro)",
      "Specifications": "BS 3262 compliant, or any other specification on request",
      "Luminance": "> 70",
      "Softening Point": "102.5° C ± 9.5° C",
      "Application Temp": "160° C - 200° C",
      "Standard Colors": "White / Yellow",
      "Packaging": "25 Kg HDPE Bags",
      "Shelf Life": "12 Months (Store in dry area)",
      "Key Benefits": "High Durability, Excellent Adhesion, Superior Visibility, Quick Drying Time"
    }
  },
  {
    id: "prod-kataline-traffix-plus",
    views: 1066,
    likes: 202,
    brand: "kataline",
    name: "Kataline Traffix Plus Thermoplastic Road Marking Paint (BS 3262 Plus)",
    category: "marking-paint",
    image: "assets/kataline_traffix_plus.png",
    specDiagram: "assets/kataline_paint_spec.jpg",
    description: "Premium-grade thermoplastic marking compound compliant with BS 3262. Specially formulated with higher luminance (>75) and maximum glass bead retroreflectivity for ultra-durable lane delineation and highway markings.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: false,
    moq: 40, // 1 Ton (25kg x 40 bags)
    specs: {
      "Product Grade": "Premium Grade (Traffix Plus)",
      "Specifications": "BS 3262 compliant, or any other specification on request",
      "Luminance": "> 75",
      "Softening Point": "102.5° C ± 9.5° C",
      "Application Temp": "160° C - 200° C",
      "Standard Colors": "White / Yellow",
      "Packaging": "25 Kg HDPE Bags",
      "Shelf Life": "12 Months (Store in dry area)",
      "Key Benefits": "High Durability, Excellent Adhesion, High Softening Point, Quick Drying Time"
    }
  },
  {
    id: "prod-kataline-traffix-o",
    views: 2331,
    likes: 560,
    brand: "kataline",
    name: "Kataline Traffix O Thermoplastic Road Marking Paint (MORTH / AASHTO / BSEN)",
    category: "marking-paint",
    image: "assets/kataline_traffix_o.png",
    specDiagram: "assets/kataline_paint_spec.jpg",
    description: "Elite Premium Grade Thermoplastic Paint meeting MORTH, AASHTO M 249, and BSEN 1436 standard specifications. Engineered for critical expressways, smart cities, and airport markings with maximum luminance (>85).",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: true,
    moq: 40, // 1 Ton (25kg x 40 bags)
    specs: {
      "Product Grade": "Elite Grade (Traffix O)",
      "Specifications": "MORTH / AASHTO M 249 / BSEN 1436 compliant, or any other specification on request",
      "Luminance": "> 85",
      "Softening Point": "102.5° C ± 9.5° C",
      "Application Temp": "160° C - 200° C",
      "Standard Colors": "White / Yellow",
      "Packaging": "25 Kg HDPE Bags",
      "Shelf Life": "12 Months (Store in dry area)",
      "Key Benefits": "High Durability, Excellent Adhesion, Maximum Luminance, High Skid Resistance"
    }
  },
  {
    id: "prod-swarco-glass-beads",
    views: 1492,
    likes: 337,
    brand: "swarco",
    name: "Swarco Glass Beads",
    category: "marking-paint",
    image: "assets/swarco_glass_beads.png",
    specDiagram: "assets/swarco_glass_beads_spec.png",
    description: "Premium Swarcoflex glass beads engineered to deliver excellent retro-reflective values for increased road safety. Ideal for drop-on or premix use in all thermoplastic and cold-applied road markings.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: true,
    moq: 40, // 1 Ton (25kg x 40 bags)
    specs: {
      "Product Name": "Swarcoflex® Glass Beads",
      "Manufacturer": "M. Swarovski GmbH / Swarco Road Marking Systems",
      "Diameter Range": "1 to 850 μm",
      "Characteristics": "Standard glass beads with very good retro-reflective values",
      "Recommendations": "Suitable for all types of road markings (highways, cities, runways)",
      "Standard Compliance": "EN 1423 / EN 1424 compliant, BS 6088, AASHTO M247",
      "Packaging": "25 Kg Net Weight Bags",
      "Made In": "Made in India",
      "Key Benefits": "Excellent day/night visibility, highly durable retroreflectivity, optimum sizing distribution"
    }
  },
  {
    id: "prod-kataline-trackmark-wr",
    views: 1417,
    likes: 461,
    brand: "kataline",
    name: "Kataline Trackmark WR Acrylic Water Based Road/Kerb Marking Paint",
    category: "marking-paint",
    image: "assets/kataline_trakmark_bucket.png",
    specDiagram: "assets/kataline_kerb_paint_spec.png",
    description: "Premium water-based acrylic resin road and kerb marking paint engineered for structures, pavements, and adjacent borders. Delivering high visibility, quick drying, and extreme durability in all weather conditions.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: true,
    moq: 10, // 200 Ltr (20L x 10 buckets)
    specs: {
      "Product Name": "Trackmark WR",
      "Finish Type": "Matt Finish",
      "Chemical Base": "Acrylic Resin (Water-Based)",
      "Standard Compliance": "IS 164 certified",
      "Coverage Capacity": "4 - 6 m²/Ltr at WFT 200 Micron",
      "Drying Time (@25°C)": "5 - 10 Minutes (Touch Dry)",
      "Application Tools": "Airless Spray or Brush",
      "Standard Colors": "White, Yellow, Red, Blue, Green, Black",
      "Packaging Unit": "20 Ltr Buckets",
      "Key Benefits": "High visibility, eco-friendly water base, highly durable in all weather, excellent night reflective compatibility"
    }
  },
  {
    id: "prod-kataline-trackmark-fg",
    views: 1281,
    likes: 310,
    brand: "kataline",
    name: "Kataline Trackmark FG Acrylic Water Based Gloss Road/Kerb Marking Paint",
    category: "marking-paint",
    image: "assets/kataline_trakmark_bucket.png",
    specDiagram: "assets/kataline_kerb_paint_spec.png",
    description: "Premium water-based acrylic resin gloss road and kerb marking paint engineered for pavement structures, adjacent barriers, and highway kerbs. Delivers full gloss finish, fast dry time, and excellent weather resistance.",
    isAuthorized3MPartner: false,
    trustBadge: "Industrial Quality",
    isBestSeller: false,
    moq: 10, // 200 Ltr (20L x 10 buckets)
    specs: {
      "Product Name": "Trackmark FG",
      "Finish Type": "Full Gloss Finish",
      "Chemical Base": "Acrylic Resin (Water-Based)",
      "Standard Compliance": "IS 164 certified",
      "Coverage Capacity": "4 - 6 m²/Ltr at WFT 200 Micron",
      "Drying Time (@25°C)": "5 - 10 Minutes (Touch Dry)",
      "Application Tools": "Airless Spray or Brush",
      "Standard Colors": "White, Yellow, Red, Blue, Green, Black",
      "Packaging Unit": "20 Ltr Buckets",
      "Key Benefits": "Elegant full gloss sheen, highly durable acrylic water base, excellent adhesion, high resistance to vehicle fuel and tires"
    }
  },
  {
    id: "prod-kataline-plastritrak-sp",
    views: 1177,
    likes: 207,
    brand: "kataline",
    name: "Kataline Plastritrak-SP Cold Plastic Road Marking Paint",
    category: "marking-paint",
    image: "assets/kataline_plastitrak_sp.png",
    specDiagram: "assets/kataline_cold_plastic_spec.png",
    description: "High-performance 2-pack cold curing solvent-free compound based on acrylic resin, engineered for mechanized spray applications. Delivers outstanding durability and excellent retroreflectivity for highways and high-volume junctions.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: false,
    moq: 20, // 400 Kg (20kg x 20 buckets)
    specs: {
      "Product Name": "Plastritrak-SP",
      "Application Type": "Mechanized Spray Application",
      "Chemical Base": "2-Pack Cold Curing Solvent-Free Acrylic Compound",
      "Standard Compliance": "MORTH / IRC 35-2015, BSEN 1436 compliant",
      "Thickness Range": "0.5 - 1.0 mm",
      "Area of Application": "Low traffic areas, Chevrons, Airport Taxiways, Aprons, Horizontal Road Signages",
      "Standard Colors": "White, Yellow, Blue, Green, Red, Purple (others on request)",
      "Packaging Unit": "20 Kg Buckets",
      "Key Benefits": "Solvent-free curing, quick set, excellent adhesion to asphalt/concrete, high solar resistance"
    }
  },
  {
    id: "prod-kataline-plastritrak-sc",
    views: 1669,
    likes: 567,
    brand: "kataline",
    name: "Kataline Plastitrak-SC Cold Plastic Screed Marking Paint",
    category: "marking-paint",
    image: "assets/kataline_plastitrak_sc.png",
    specDiagram: "assets/kataline_cold_plastic_spec.png",
    description: "Premium 2-component solvent-free cold plastic screed paint engineered for high-performance highway markings. Perfect for centerlines and edge markings, creating a highly visible and extremely durable safety profile.",
    isAuthorized3MPartner: false,
    trustBadge: "TrustSeal Verified",
    isBestSeller: true,
    moq: 20, // 400 Kg (20kg x 20 buckets)
    specs: {
      "Product Name": "Plastritrak-SC",
      "Application Type": "Mechanized Screed Application",
      "Chemical Base": "2-Component Cold Curing Solvent-Free Acrylic Compound",
      "Standard Compliance": "MORTH / IRC 35-2015, BSEN 1436 compliant",
      "Thickness Range": "1.5 - 3.0 mm",
      "Area of Application": "Centre line & Edge line Markings",
      "Standard Colors": "White, Yellow, Blue, Green, Red, Purple (others on request)",
      "Packaging Unit": "20 Kg Buckets",
      "Key Benefits": "Heavy-duty wear profile, precise screed thickness, long-term retroreflectivity retaining, oil/fuel resistant"
    }
  },
  {
    id: "prod-kataline-plastritrak-rc",
    views: 1024,
    likes: 178,
    brand: "kataline",
    name: "Kataline Plastitrak-RC Cold Plastic Roll-On Paint",
    category: "marking-paint",
    image: "assets/kataline_plastitrak_rc.png",
    specDiagram: "assets/kataline_cold_plastic_spec.png",
    description: "Premium 2-component solvent-free cold plastic paint engineered for manual roller applications. Ideal for cycle tracks, pedestrian crossings, and walkway bus lanes, delivering highly vibrant non-skid color boundaries.",
    isAuthorized3MPartner: false,
    trustBadge: "Industrial Quality",
    isBestSeller: false,
    moq: 20, // 400 Kg (20kg x 20 buckets)
    specs: {
      "Product Name": "Plastritrak-Rc",
      "Application Type": "Manual Roller Application",
      "Chemical Base": "2-Component Cold Curing Solvent-Free Acrylic Compound",
      "Standard Compliance": "MORTH / IRC 35-2015, BSEN 1436 compliant",
      "Thickness Range": "1.0 - 2.0 mm",
      "Area of Application": "Cycle Tracks, Walkways, Bus Lanes, Pedestrian Crossings, Horizontal Road Signages",
      "Standard Colors": "White, Yellow, Blue, Green, Red, Purple (others on request)",
      "Packaging Unit": "20 Kg Buckets",
      "Key Benefits": "Excellent anti-skid texturing, easy manual installation, vibrant color stability, high friction coefficient"
    }
  },
  {
    id: "prod-kataline-plastirib-2k",
    views: 1091,
    likes: 360,
    brand: "kataline",
    name: "Kataline Plastirib 2K Cold Plastic Ribbon Paint",
    category: "marking-paint",
    image: "assets/kataline_plastirib_2k.png",
    specDiagram: "assets/kataline_cold_plastic_spec.png",
    description: "Premium 2-component cold plastic ribbon paint engineered to create structured, audio-tactile warning profiles. Ideal for edge-line profile markings and lane alert strips on highways and expressways.",
    isAuthorized3MPartner: false,
    trustBadge: "Industrial Quality",
    isBestSeller: false,
    moq: 20, // 400 Kg (20kg x 20 buckets)
    specs: {
      "Product Name": "Plastirib 2K",
      "Application Type": "Structured / Audio-Tactile Ribbon Application",
      "Chemical Base": "2-Component Cold Curing Solvent-Free Acrylic Compound",
      "Standard Compliance": "MORTH / IRC 35-2015 compliant",
      "Thickness Range": "2.0 - 5.0 mm (ribbed profile)",
      "Area of Application": "Highway edge-lines, auditory warning strips, lane exit warning blocks",
      "Standard Colors": "White, Yellow (others on request)",
      "Packaging Unit": "20 Kg Buckets",
      "Key Benefits": "Creates auditory and tactile vibration alerts, extreme high-build durability, excellent retroreflectivity under rainy night conditions"
    }
  }
,
  {
    id: "prod-square-base-750",
    views: 1069,
    likes: 343,
    brand: "detco",
    name: "Traffic Cone",
    category: "traffic-cones",
    image: "assets/detco_square_base_cone.png",
    description: "Manufactured in high-visibility Red, Blue, or Orange options. Engineered with a square base (390x390mm), 4/6 inch sleeves, and weighing up to 3.5kg. Delivers premium stability for heavy-duty B2B traffic and utility operations.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Base Dimensions": "390 x 390 mm",
      "Sleeve Width": "4\" / 6\" Dual Reflective Sleeves",
      "Product Weight": "1.2 kg / 3.5 kg weighted options",
      "Product Height": "750 mm (approx. 30 inches)",
      "Available Colors": "Red, Blue, or Orange",
      "Logo Markings": "Official DETCO D C Shield Logo",
      "Material": "High-Durability Flexible Polymer",
      "Compliance": "IRC Highway Safety Standards"
    }
  },
  {
    id: "prod-square-base-1000",
    views: 1177,
    likes: 187,
    brand: "detco",
    name: "Traffic Cone 1000mm",
    category: "traffic-cones",
    image: "assets/detco_1000mm_cone.png",
    description: "Elite 1-meter high-stability red traffic cone weighing 5kg. Outfitted with an 11-inch wide reflective collar, high-density square base, and direct DETCO logo shield branding. Designed for national highway and expressway infrastructure.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: true,
    moq: 10,
    specs: {
      "Base Dimensions": "490 x 490 mm",
      "Sleeve Width": "11\" High-Intensity Prismatic Sleeve",
      "Product Weight": "5 kg (Extreme Stability)",
      "Product Height": "1000 mm (approx. 40 inches)",
      "Product Color": "High-Visibility Safety Red",
      "Base Design": "Heavy-Duty Weighted Square Base",
      "Logo Markings": "Official DETCO D C Shield print on body",
      "Compliance": "NHAI, MSRDC, PWD, and IRC Highway Guidelines"
    }
  },
  {
    id: "prod-plastic-bollard",
    views: 1954,
    likes: 599,
    brand: "detco",
    name: "Plastic Bollard",
    category: "traffic-cones",
    image: "assets/detco_plastic_bollard.png",
    description: "Engineered with high-impact elastomeric polymers and NHAI-compliant retroreflective collars. Features a heavy hexagonal vulcanized rubber base (6.5kg) for absolute stability on airport runways, highway divisions, and municipal parking zones. Includes a built-in top carry handle.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Product Height": "1200 mm",
      "Base Design": "Hexagonal Rubber Base",
      "Product Weight": "6.5 kg",
      "Reflective Tape": "3\" x 2 pcs",
      "Belt Color Options": "Red / Blue retractable belt",
      "Logo Markings": "Official DETCO D C Shield Logo print",
      "Material": "High-Impact Flexible Polymer post",
      "Compliance": "Highway traffic delineator guidelines"
    }
  },
  {
    id: "prod-spring-post-base",
    views: 951,
    likes: 325,
    brand: "detco",
    name: "DETCO Unbreakable Cone",
    category: "traffic-cones",
    image: "assets/detco_spring_post_base.png",
    description: "Designed as a dual-post modular delineator system mounted on heavy-duty yellow and black speed-bump-style rectangular bases (800 x 200 mm). The orange posts are 450mm high with dual microprismatic reflective collars, delivering superior lane channeling and impact resilience.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Pole Height": "450 mm",
      "Base Length": "800 mm",
      "Base Width": "200 mm",
      "Pole Color": "High-Visibility Safety Orange",
      "Base Color": "Yellow & Black speed-bump markings",
      "Logo Markings": "Official DETCO D C Shield print on post",
      "Material": "High-Impact Elastomeric Polymer post with heavy vulcanized rubber base",
      "System Weight": "Heavy speed-bump base for high impact resistance"
    }
  },
  {
    id: "prod-folding-barricade",
    views: 925,
    likes: 254,
    brand: "detco",
    name: "Folding Barricade",
    category: "traffic-cones",
    image: "assets/detco_folding_barricade.jpg",
    physicalImage: "assets/detco_folding_barricade_physical.jpg",
    description: "Engineered with high-durability polymer links expanding up to a full 2.5 meters. Designed in safety yellow with high-visibility red reflective safety warnings. Features a water-fillable ballast base to increase total weight to 7kg for maximum stability in high-wind zones.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: true,
    moq: 10,
    specs: {
      "Product Height": "950 mm",
      "Open Length": "2.5 meters",
      "Closed Length": "450 mm (highly compact storage)",
      "Product Weight": "3.0 kg (Empty) / 7.0 kg (Water-Filled Ballast)",
      "Product Color": "High-Visibility Safety Yellow with Red/Reflective chevrons",
      "Special Feature": "Water-Fillable Chamber for enhanced wind stability",
      "Material": "High-Impact UV-Stabilized Polymer",
      "Application": "Crowd control routing, hazardous excavation cordoning, industrial zone partition"
    }
  },
  {
    id: "prod-que-manager",
    views: 2009,
    likes: 358,
    brand: "detco",
    name: "Que Managers",
    category: "traffic-cones",
    image: "assets/detco_que_manager.png",
    physicalImage: "assets/detco_que_manager_physical.jpg",
    description: "Premium stainless steel crowd control stanchions equipped with retractable safety belts. Features a heavy circular base (8kg) measuring 320x320mm for excellent stability. Available with Red or Blue 2-meter or 2.75-meter belts for flexible crowd management.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Stanchion Diameter": "63 mm",
      "Base Dimensions": "320 x 320 mm circular",
      "Product Weight": "8 kg stanchion & weighted base",
      "Belt Size Options": "2 meters / 2.75 meters length",
      "Belt Color": "Red / Blue high-strength woven fabric",
      "Stanchion Material": "Premium mirror-polished Stainless Steel",
      "Base Design": "Floor-protecting rubberized heavy base",
      "Application": "Airport queues, metro stations, bank lobby crowd routing"
    }
  },
  {
    id: "prod-golden-que-manager",
    views: 1494,
    likes: 286,
    brand: "detco",
    name: "Golden Que Managers",
    category: "traffic-cones",
    image: "assets/detco_golden_que_manager.png",
    description: "Elite polished brass-finish stanchions paired with a luxury red velvet rope. Built with an 8kg circular base measuring 320x320mm and standing 886mm high. Ideal for VIP access routing, premium B2B hotel lobbies, and upscale event zoning.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Pole Height": "886 mm",
      "Stanchion Diameter": "51 mm",
      "Base Dimensions": "320 x 320 mm circular",
      "Product Weight": "8 kg stanchion & weighted base",
      "Velvet Rope Length": "1.5 meters premium rope",
      "Belt/Rope Color": "Luxury Red Velvet with gold clip hooks",
      "Finish": "Polished mirror Gold / Brass finish",
      "Base Design": "Heavy-duty dome base with rubber floor protector",
      "Best For": "VIP crowd control, luxury hotel lobbies, corporate entry gates"
    }
  },
  {
    id: "prod-reflective-jacket",
    views: 879,
    likes: 155,
    brand: "detco",
    name: "Reflective Jacket",
    category: "traffic-cones",
    image: "assets/detco_reflective_jacket.png",
    description: "NHAI-compliant professional reflective jacket designed for highway construction and utility engineers. Made from lightweight, breathable mesh fabric available in GSM options of 60, 80, or 100. Outfitted with high-contrast dual reflective silver tape bands in Orange or Green colors. Supports custom B2B corporate logo printing.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Size": "Standard Free Size / 1/2 inch reflective tape detailing",
      "GSM Options": "60 / 80 / 100 high-strength fabric weight",
      "Color Options": "Fluorescent Orange & Neon Green",
      "Reflective Tape": "Dual vertical & horizontal high-contrast silver bands",
      "Printing Compatibility": "Available for custom B2B corporate logo printing",
      "Material": "Lightweight breathable polyester mesh fabric",
      "Closure": "Heavy-duty durable front zip closure",
      "Compliance": "NHAI, PWD, and IRC roadway worker safety specifications"
    }
  },
  {
    id: "prod-speed-breaker-250",
    views: 1917,
    likes: 625,
    brand: "detco",
    name: "Highway Speed Breaker",
    category: "speed-breakers",
    image: "assets/detco_speed_breaker_250.png",
    gallery: [
      { src: "assets/detco_speed_breaker_250_installation.jpg?v=32.0", alt: "Highway Speed Breaker Road Installation" }
    ],
    description: "Engineered for toll plazas and highway checkpoints. Constructed from vulcanized rubber with yellow/black segments. Measures L 250mm x W 350mm x H 50mm, weighing 18.5kg. Fits 4 pieces per meter, secured via 16 high-tensile fixing nails.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Length x Width x Height": "250 mm x 350 mm x 50 mm",
      "Unit Weight": "18.5 kg",
      "Density/Pieces per Meter": "4 pieces",
      "Fixing System": "16 nails required per meter",
      "Material": "Heavy-Duty Vulcanized Rubber Compound",
      "Color Pattern": "Alternating yellow and black segments",
      "Compression Strength": "Compliant with highway heavy axle limits",
      "Compliance": "IRC & MORTH highway guidelines"
    }
  },
  {
    id: "prod-speed-breaker-500",
    views: 1768,
    likes: 486,
    brand: "detco",
    name: "Rubber Speed Breaker",
    category: "speed-breakers",
    image: "assets/detco_speed_breaker_500.png",
    description: "Highly durable speed bump designed for private warehouse avenues, tech park ramps, and housing society gates. Measures L 500mm x W 350mm x H 50mm, weighing 16kg. Fits 2 pieces per meter, requiring 8 fixing nails per set.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Length x Width x Height": "500 mm x 350 mm x 50 mm",
      "Unit Weight": "16.0 kg",
      "Density/Pieces per Meter": "2 pieces",
      "Fixing System": "8 nails required per meter",
      "Material": "UV-Stabilized High-Density Solid Rubber",
      "Reflectivity": "Molded bright yellow contrast segments",
      "Application": "Industrial warehouses, tech parks, housing society roads"
    }
  },
  {
    id: "prod-speed-breaker-750",
    views: 947,
    likes: 145,
    brand: "detco",
    name: "Rubber Speed Breaker",
    category: "speed-breakers",
    image: "assets/detco_speed_breaker_750.png",
    description: "Extra-wide heavy-duty speed bump featuring high-contrast molded arrows and embedded glass bead retroreflective lane-markers. Measures L 500mm x W 400mm x H 75mm, weighing 26kg. Delivers vehicle deceleration for municipal roads.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: true,
    moq: 10,
    specs: {
      "Length x Width x Height": "500 mm x 400 mm x 75 mm",
      "Unit Weight": "26.0 kg (Extreme Deceleration)",
      "Density/Pieces per Meter": "2 pieces",
      "Fixing System": "8 nails required per meter",
      "Reflective Detailing": "Molded directional white chevron arrows & glass bead lane markers",
      "Material": "High-Impact Shock-Absorbing Solid Elastomer",
      "Best For": "Municipal roads, pedestrian crossings, school zones"
    }
  },
  {
    id: "prod-speed-breaker-endcap",
    views: 1855,
    likes: 345,
    brand: "detco",
    name: "Rubber End Cap",
    category: "speed-breakers",
    image: "assets/detco_speed_breaker_endcap.jpg",
    description: "Pre-formed semi-circular rubber terminal caps designed to finish speed hump corridors cleanly and protect vehicle tires. Measures L 150mm x W 350mm x H 50mm, weighing 2kg. Sold in matching yellow and black segments.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Length x Width x Height": "150 mm x 350 mm x 50 mm",
      "Unit Weight": "2.0 kg per cap",
      "Density/Pieces per Meter": "2 pieces",
      "Material": "Pre-formed vulcanized impact-resistant rubber",
      "Design": "Sleek tapered semi-circular slope to protect tires",
      "Colors": "Matching Yellow / Black pairs"
    }
  },
  {
    id: "prod-rumble-strip",
    views: 1926,
    likes: 633,
    brand: "detco",
    name: "Highway Rumbling Strip",
    category: "speed-breakers",
    image: "assets/detco_rumble_strip.png",
    description: "Safety rumble strip designed to alert drivers near toll approaches, dangerous curve entries, and highway lane deviations. Measures L 500mm x W 125mm x H 25mm, weighing 4.3kg. Installs 2 pieces per meter with 6 fixing nails.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Length x Width x Height": "500 mm x 125 mm x 25 mm",
      "Unit Weight": "4.3 kg",
      "Density/Pieces per Meter": "2 pieces",
      "Fixing System": "6 nails required per meter",
      "Material": "Hardened vulcanized high-impact rubber compound",
      "Application": "Toll plaza approach alerts, speed reduction warnings, sharp curves"
    }
  },
  {
    id: "prod-white-rumbler",
    views: 1529,
    likes: 351,
    brand: "detco",
    name: "White Rumbler Strip",
    category: "speed-breakers",
    image: "assets/detco_white_rumbler.png",
    description: "NHAI-compliant premium rumble strip featuring embedded 3M retroreflective stripe markings for ultimate low-light lane alerts. Measures L 500mm x W 200mm x H 15mm, weighing 1.1kg. Delivers 25-ton load capacity with 12 nails.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Length x Width x Height": "500 mm x 200 mm x 15 mm",
      "Unit Weight": "1.1 kg",
      "Weight Bearing Capacity": "25 tons",
      "Density/Pieces per Meter": "2 pieces",
      "Fixing System": "12 nails required per meter",
      "Reflective Detailing": "Embedded dual-band 3M retroreflective strip markings",
      "Compliance": "NHAI & IRC compliant for night highway delineation"
    }
  },
  {
    id: "prod-plastic-breaker-50",
    views: 1819,
    likes: 605,
    brand: "detco",
    name: "Plastic Speed Breaker",
    category: "speed-breakers",
    image: "assets/detco_plastic_breaker_50.png",
    description: "Highly resilient thermoplastic speed bump designed for internal pathways, campus roads, and retail parkways. Measures L 500mm x W 390mm x H 50mm, weighing 3kg. Fits 2 pieces per meter, secured via 12 high-durability fixing bolts.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Length x Width x Height": "500 mm x 390 mm x 50 mm",
      "Unit Weight": "3.0 kg",
      "Density/Pieces per Meter": "2 pieces",
      "Fixing System": "12 bolts required per meter",
      "Material": "High-Impact UV-Stabilized Thermoplastic",
      "Color Pattern": "Alternating yellow and black segments",
      "Application": "Corporate campuses, internal roads, shopping malls"
    }
  },
  {
    id: "prod-plastic-breaker-75",
    views: 1365,
    likes: 238,
    brand: "detco",
    name: "Plastic Speed Breaker",
    category: "speed-breakers",
    image: "assets/detco_plastic_breaker_75.png",
    description: "Engineered with high-impact molded thermoplastic polymer with retroreflective lens markers for maximum low-light lane visibility. Measures L 500mm x W 390mm x H 75mm, weighing 3.5kg. Fits 2 pieces per meter with 12 bolts.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Length x Width x Height": "500 mm x 390 mm x 75 mm",
      "Unit Weight": "3.5 kg",
      "Density/Pieces per Meter": "2 pieces",
      "Fixing System": "12 bolts required per meter",
      "Reflective Detailing": "Molded retroreflective cat-eye lens markers",
      "Material": "Heavy-Duty Engineering Plastic Polymer",
      "Compliance": "Standard municipal vehicle deceleration guidelines"
    }
  },
  {
    id: "prod-plastic-breaker-250",
    views: 1096,
    likes: 316,
    brand: "detco",
    name: "Plastic Speed Breaker",
    category: "speed-breakers",
    image: "assets/detco_plastic_breaker_250.png",
    description: "Heavy-duty extra-long plastic speed breaker module built to withstand high vehicle axle loads in airport lanes and toll divisions. Measures L 250mm x W 750mm x H 75mm, weighing 7kg. Installs 4 pieces per meter with 16 fixing nails.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Length x Width x Height": "250 mm x 750 mm x 75 mm",
      "Unit Weight": "7.0 kg",
      "Density/Pieces per Meter": "4 pieces",
      "Fixing System": "16 nails required per meter",
      "Material": "Ultra-Tough Solid Engineering Plastic",
      "Application": "Toll plazas, airports, industrial zones with heavy vehicle axle traffic"
    }
  },
  {
    id: "prod-plastic-endcap",
    views: 2073,
    likes: 331,
    brand: "detco",
    name: "Plastic End Cap",
    category: "speed-breakers",
    image: "assets/detco_plastic_endcap.jpg",
    description: "Pre-formed semi-circular thermoplastic terminal end caps designed to lock cleanly onto the speed bump segments. Measures L 150mm x W 350mm x H 50mm, weighing 400 grams. Secured via 2 fixing bolts per cap.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Length x Width x Height": "150 mm x 350 mm x 50 mm",
      "Unit Weight": "400 grams per cap",
      "Fixing System": "2 bolts required per cap",
      "Material": "High-strength impact-resistant thermoplastic",
      "Design": "Sleek tapered circular shape to finish speed hump corridors cleanly"
    }
  },
  {
    id: "prod-plastic-rumble",
    views: 1906,
    likes: 514,
    brand: "detco",
    name: "Plastic Rumbling Strip",
    category: "speed-breakers",
    image: "assets/detco_plastic_rumble.png",
    description: "High-strength safety rumbling strip designed to alert drivers in dangerous lane transitions and warehouse approaches. Measures L 500mm x W 125mm x H 25mm, weighing 2.3kg. Installs 2 pieces per meter with 6 fixing bolts.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Length x Width x Height": "500 mm x 125 mm x 25 mm",
      "Unit Weight": "2.3 kg",
      "Density/Pieces per Meter": "2 pieces",
      "Fixing System": "6 bolts required per meter",
      "Material": "UV-Stabilized High-Density Thermoplastic",
      "Application": "Dangerous intersections, toll checkpoints, lane dividers"
    }
  },
  {
    id: "prod-solar-barricading-light",
    views: 1228,
    likes: 428,
    brand: "detco",
    name: "Solar Barricading Light",
    category: "traffic-cones",
    image: "assets/detco_solar_barricading_light.jpg",
    gallery: [
      { src: "assets/detco_solar_barricading_light_installation.jpg?v=32.0", alt: "Solar Barricading Light Easy Clamp Installation Infographic" }
    ],
    description: "Advanced solar warning light featuring dual retroreflective lenses and highly resilient PP/AS weatherproof structure. Equipped with a 2.4V 1500mAH battery, 0.4W solar panel, and 4 high-brightness LEDs. Offers 60 hours of operation with flash, steady, and close modes. Rated IP68 waterproof.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: true,
    moq: 10,
    specs: {
      "Diameter / Length": "18 cm / 22.5 cm",
      "LED Count": "4 Ultra-Bright LEDs",
      "Color Pattern": "Red / Yellow",
      "Water Proof Rating": "IP-68 (Fully Weatherproof)",
      "Material": "Frame: PP (Polypropylene), Shell: AS",
      "Visibility Range": "200 meters",
      "Solar Panel": "0.4 Watt Panel",
      "Battery Capacity": "2.4V, 1500mAH Rechargeable Ni-MH",
      "Backup Time": "60 hours on full solar charge",
      "Working Modes": "Flash / Steady / Close"
    }
  },
  {
    id: "prod-solar-light-wiremesh",
    views: 1527,
    likes: 315,
    brand: "detco",
    name: "Solar Light with Wiremesh",
    category: "traffic-cones",
    image: "assets/detco_solar_light_wiremesh.jpg",
    description: "Heavy-duty warning light enclosed in a robust steel protective cage for high-impact industrial safety. Built with a polycarbonate housing and mono-crystalline 4V, 300ma solar panel. Backed by a 2 x 1.2V 1600mah battery providing 36 hours of charge. Rated IP67 waterproof.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Dimensions (Dia x H)": "85 mm x 150 mm",
      "Water Proof Rating": "IP-67 Waterproof",
      "LED Count": "4 High-Performance LEDs",
      "Color Pattern": "Red / Yellow",
      "Housing Material": "Polycarbonate with heavy steel wire mesh protective cage",
      "Solar Panel": "Mono-crystalline 4V, 300ma",
      "Battery Capacity": "2 x 1.2 Volts, 1600mah Ni-MH",
      "Backup Time": "36 hours after full solar charge",
      "Application": "Cones, Bridges, Industrial Barriers, Construction zones"
    }
  },
  {
    id: "prod-light-baton",
    views: 2331,
    likes: 745,
    brand: "detco",
    name: "Light Batons",
    category: "traffic-cones",
    image: "assets/detco_light_baton.jpg",
    description: "Premium high-visibility PVC warning wand designed for traffic management, parking marshals, and hazard signaling. Features 5-stage lighting functions (Red blinking, Red stable, Green blinking, Green stable, and White torch). Available in battery-operated or rechargeable options.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Diameter": "4 cm",
      "Length Options": "11 inch / 21 inch",
      "Battery System": "Battery Operated / Rechargeable",
      "Body Material": "High-durability PVC Pipe",
      "Warning Functions": "Red blinking, Red stable, Green blinking, Green stable, White torch",
      "Key Features": "High visibility, durable & long lasting, lightweight & easy to carry, weather resistant"
    }
  },
  {
    id: "prod-solar-stud-pc",
    views: 2065,
    likes: 561,
    brand: "detco",
    name: "Solar Road Stud",
    category: "traffic-cones",
    image: "assets/detco_solar_stud_pc.jpg",
    description: "Premium solar-powered active pavement marker featuring high-strength aluminum structural frames and protective polycarbonate caps. Available in both shanked and shankless flat-mount layouts. Rated to support up to 30 tons vehicle loads.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Mounting Design": "With anchoring shank / Without shank (flat-mount)",
      "Frame Material": "Acrylic reflector + polycarbonate (PC) cap + aluminium frame",
      "Size Dimensions": "132 x 122 x 75 mm",
      "Weight Support": "30 tons (heavy vehicle axle resistance)",
      "Visual Distance": "1000 meters",
      "Water Proof Rating": "< IP68 Waterproof",
      "Solar Panel Rating": "High-efficiency solar panel (0.3 W, 45 x 65 mm)",
      "Battery System": "Rechargeable 1.2V / 800mah Ni-MH battery",
      "Backup Capacity": "48 hours after full charge, or steady light for more than 12 hours",
      "LED Colors Available": "Red, White, or Yellow"
    }
  },
  {
    id: "prod-solar-traffic-signal",
    views: 987,
    likes: 166,
    brand: "detco",
    name: "Solar Signals",
    category: "traffic-cones",
    image: "assets/detco_solar_traffic_signal.jpg",
    description: "Premium solar-powered active LED traffic blinker signal designed for lane intersections, toll plazas, dangerous curves, and municipal boundary zones. Outfitted with 192 ultra-bright LEDs for superior day/night visibility, a robust 20W solar panel, and integrated visor hood.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Blinker Size": "300 mm Diameter (with high-visibility visor)",
      "LED Count": "192 Nos. of High-Intensity LEDs",
      "Battery Capacity": "12 Volt, 7Ah (Ni-MH rechargeable battery provides power back for 1-2 days)",
      "Solar Panel Rating": "20 Watt High-Efficiency Solar Panel",
      "Standard Accessories": "Includes Solar Panel clamp, Hose Clamps, and mounting brackets",
      "LED Colors Available": "Red, Amber, or Green"
    }
  },
  {
    id: "prod-guard-rail-reflector",
    views: 1239,
    likes: 222,
    brand: "detco",
    name: "Guard Rail Reflector",
    category: "traffic-cones",
    image: "assets/detco_guard_rail_reflector.png",
    description: "High-visibility trapezoidal highway guardrail reflector made of premium aluminum sheeting. Supports single or double-sided reflectivity with 3M EGP, HIP, or DG microprismatic retroreflective films. Designed for ultimate weather resistance and effortless installation.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Base Material": "Premium Quality Aluminum Sheet",
      "Reflective Face Options": "Single / Both Side",
      "Reflective Material": "3M EGP / 3M HIP / 3M DG Microprismatic Films",
      "Dimensions (Top x Bottom x H)": "Top Width: 120 mm, Bottom Width: 50 mm, Length: 65 mm",
      "Weather Resistance": "Excellent UV and extreme weather proofing",
      "Installation": "Easy slot mounting on standard guard rails"
    }
  },
  {
    id: "prod-wheel-lock-car",
    views: 1456,
    likes: 225,
    brand: "detco",
    name: "Wheel Lock",
    category: "traffic-cones",
    image: "assets/detco_wheel_lock_car.jpg",
    description: "High-security anti-theft claw clamp designed for passenger vehicles and sedans. Built from heavy-gauge structural steel sheet with a bright red/yellow weather-proof coating. Adjustable locking area from 175mm to 275mm. Comes with 3 secure keys.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Total Length": "485 mm",
      "Total Width": "275 mm",
      "Lock Area Range": "175 - 275 mm",
      "Key Count": "3 High-Security Keys",
      "Application Class": "Small passenger cars & sedans",
      "Material / Finish": "Heavy-Duty Steel with Rust-Resistant Yellow & Red Powder Coating",
      "Features": "Anti-theft heavy-duty design, strong & durable, easy to use"
    }
  },
  {
    id: "prod-wheel-lock-truck",
    views: 1492,
    likes: 476,
    brand: "detco",
    name: "Truck Wheel Lock",
    category: "traffic-cones",
    image: "assets/detco_wheel_lock_truck.jpg",
    description: "Industrial-grade, anti-theft heavy vehicle clamp clamp for large commercial trucks, trailers, and buses. Made from thick reinforced heavy-duty square steel bars. Accommodates tires up to 500mm wide and weighs 3 kg for high durability.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: true,
    moq: 10,
    specs: {
      "Block Height": "60 mm",
      "Clamp Length": "475 mm",
      "Clamp Width": "400 mm",
      "Maximum Tyre Width": "Up to 500 mm profile",
      "Product Weight": "3.0 kg (Heavy Duty)",
      "Material / Finish": "Thick Reinforced Structural Steel with Bright Yellow Powder Coating",
      "Features": "Anti-theft heavy-duty design, strong & durable, easy to use"
    }
  },
  {
    id: "prod-u-corner-guard",
    views: 1727,
    likes: 581,
    brand: "detco",
    name: "U Shape Corner Guard",
    category: "traffic-cones",
    image: "assets/detco_u_corner_guard.jpg",
    description: "Heavy-duty U-shaped rubber column protector designed to absorb severe vehicle impacts in narrow parking garages, loading docks, and warehouses. Features high-quality retroreflective yellow chevron tapes and a 30mm thick vulcanized rubber body.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Protector Width": "100 x 100 mm",
      "Protector Thickness": "30 mm",
      "Standard Heights": "1000 mm / 1200 mm",
      "Reflective Tapes": "60mm wide premium reflective tapes (6 tapes for 1000mm, 8 tapes for 1200mm)",
      "Features": "High impact resistant, premium reflective visibility, weather resistant, easy to install, durable & long lasting"
    }
  },
  {
    id: "prod-l-corner-guard",
    views: 1646,
    likes: 463,
    brand: "detco",
    name: "L Shape Corner Guard",
    category: "traffic-cones",
    image: "assets/detco_l_corner_guard.jpg",
    description: "Industrial-grade L-shaped rubber corner guard designed to secure wall corners and square pillars from vehicle scrapes. Constructed from tough vulcanized rubber with thickness options of 6mm, 8mm, or 10mm. Equipped with high-visibility chevron safety tapes.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Corner Width": "100 x 100 mm",
      "Thickness Options": "6 mm / 8 mm / 10 mm",
      "Standard Heights": "800 mm / 1000 mm / 1200 mm",
      "Reflective Tapes": "70mm wide high-quality reflective tapes (4 tapes for 800mm, 5 tapes for 1000mm, 6 tapes for 1200mm)",
      "Features": "High impact resistant, premium reflective visibility, weather resistant, easy to install, durable & long lasting"
    }
  },
  {
    id: "prod-convex-mirror",
    views: 2123,
    likes: 329,
    brand: "detco",
    name: "Convex Mirror",
    category: "traffic-cones",
    image: "assets/detco_convex_mirror.jpg",
    gallery: [
      { src: "assets/convex_mirror_variants.png?v=1.2", alt: "Convex Mirror Size Variations" },
      { src: "assets/convex_mirror_installation.png?v=1.2", alt: "Convex Mirror Roadway Curve Installation" }
    ],
    description: "Premium wide-angle convex safety mirror constructed with an unbreakable polycarbonate lens and high-visibility orange protective hood. Delivers dynamic 130-degree viewing area for blind spots, parking turns, driveways, and security checks.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Lens Material": "Unbreakable Premium Polycarbonate",
      "Diameter Sizes": "18 / 22 / 24 / 30 / 32 / 40 inches",
      "Shell Cover": "All-weather high-impact ABS with integrated sun/rain hood",
      "Viewing Area": "130-degree wide angle view",
      "Key Benefits": "Wide angle view, durable & impact resistant, weather resistant, unbreakable lens, easy to install"
    }
  },
  {
    id: "prod-rubber-wheel-stopper",
    views: 1352,
    likes: 380,
    brand: "detco",
    name: "Rubber Wheel Stopper",
    category: "traffic-cones",
    image: "assets/detco_rubber_wheel_stopper.jpg",
    description: "Premium solid rubber parking wheel stopper designed to regulate vehicular parking safety in commercial garages, retail spaces, and corporate driveways. Constructed from highly impact-resistant vulcanized rubber compound. Features high-quality retroreflective yellow stripes for extreme night visibility.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Dimensions (L x W x H)": "600 x 120 x 100 mm",
      "Reflective Detailing": "60mm x 1 tape + 35mm x 2 tapes high-quality reflective tape",
      "Stopper Weight": "3.5 kg",
      "Material Used": "High-impact vulcanized natural/synthetic rubber compound",
      "Key Benefits": "High impact resistant, high quality reflective tape, weather resistant, easy to install, durable & long lasting"
    }
  },
  {
    id: "prod-cone-message-plate",
    views: 1882,
    likes: 639,
    brand: "detco",
    name: "Cone Message Plate",
    category: "traffic-cones",
    image: "assets/detco_cone_message_plate.jpg",
    description: "Highly durable warning message plate designed to interlock over standard cone tops. Features a 400x300mm orange layout and a 375x180mm customizable print space for highway safety warnings.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Plate Dimensions": "400 x 300 mm",
      "Print Area": "375 x 180 mm",
      "Material": "Heavy-Duty High-Impact Polymer (UV Stabilized)",
      "Product Color": "High-Visibility Safety Orange",
      "Mounting sleeve": "Secure interlocking collar fits over standard cone tops",
      "Application": "Highway detour signage, municipal hazards, custom B2B printing"
    }
  },
  {
    id: "prod-link-chain",
    views: 1625,
    likes: 533,
    brand: "detco",
    name: "Link Chain",
    category: "traffic-cones",
    image: "assets/detco_link_chain.png",
    description: "High-strength plastic link chain in alternating red and white warning colors. Available in 6mm and 8mm thickness options. Ideal for crowd control, parking, and construction zoning.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Material": "High-Density Polyethylene (HDPE)",
      "Thickness Options": "6mm / 8mm High Strength Links",
      "Color Pattern": "Alternating Red and White links",
      "Length Options": "50m roll / Custom cut lengths",
      "Product Weight": "Tough lightweight crowd and zone control barrier",
      "Best For": "Crowd routing, construction excavation zones, industrial spaces"
    }
  },
  {
    id: "prod-connecting-rod",
    views: 2062,
    likes: 392,
    brand: "detco",
    name: "Connecting Rod",
    category: "traffic-cones",
    image: "assets/detco_connecting_rod.png",
    description: "Extendable safety connector rod equipped with pre-formed end loops. Extends to a full 2 meters (collapses to 1 meter). Available in Black/Yellow or Red/White safety warning stripes.",
    isAuthorized3MPartner: false,
    trustBadge: "DETCO Certified",
    isBestSeller: false,
    moq: 10,
    specs: {
      "Extensible Length": "Open: 2.0 meters, Closed: 1.0 meter (retractable)",
      "Color Options": "Black/Yellow or Red/White high-visibility warning stripes",
      "Ring End Diameter": "100 mm pre-formed loops fits standard cones",
      "Material": "Lightweight, high-impact PVC with heavy-duty loop ends",
      "Application": "Rapid parking zoning, trench markers, roadside utility lines"
    }
  }
];

// Export for module systems if needed, but also attach to window for vanilla browser access
if (typeof module !== 'undefined' && module.exports) {
  module.exports = products;
} else {
  window.productsData = products;
}
